# Generated by Django 4.0.2 on 2022-04-07 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_formdaily_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdaily',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
