# Generated by Django 4.0.2 on 2022-04-09 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_alter_formdaily_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='dateDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='formularioDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=2500)),
                ('q2', models.CharField(max_length=2500)),
                ('q3', models.CharField(max_length=2500)),
                ('date_daily', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.datedaily')),
            ],
        ),
        migrations.DeleteModel(
            name='formDaily',
        ),
    ]
