# Generated by Django 4.0.2 on 2022-04-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_datedaily_formulariodaily_delete_formdaily'),
    ]

    operations = [
        migrations.AddField(
            model_name='datedaily',
            name='user',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
